### ISSUE TITLE
Update docs w.r.t. #8490 pfSense-pkg-acme: acme_certificates_edit.php - Add ability to specify (vs generate) private key

### ISSUE THREAD

**Issue by mr-intj** [pfsense/docs#13]
Need to document the new support for users specifying their own private keys:

    #8490 pfSense-pkg-acme: acme_certificates_edit.php - Add ability to specify (vs generate) private key

Unless anyone has any alternate suggestions, I'm starting work on this shortly.

**Comment by jim-p** [comment]
I just updated and restructured the ACME docs. I mentioned this in passing when I did. It may be good enough, or maybe we could stick an extra paragraph about it somewhere else in there.

We can close this out if what is there now is OK.

**Comment by mr-intj** [comment]
Looks good to me.
