### ISSUE TITLE
Add comment on "Filter rule association" in DNS Redirection documentation

### ISSUE THREAD

**Issue by jamcafee** [pfsense/docs#16]
Suggest updating the "Redirecting all DNS Requests to pfSense" documentation to include the value for the "Filter rule association" setting when creating the NAT Port Forward rule.  Screenshot in the documentation stops just before that setting and some users may not properly set it / change it.

https://www.netgate.com/docs/pfsense/dns/redirecting-all-dns-requests-to-pfsense.html

**Comment by jim-p** [comment]
That setting is really up to the user. In most cases, outbound traffic is already allowed so it's not relevant. In cases where the user has setup custom rules, they may prefer to handle it some other way. The text already mentions that the traffic needs to be passed, just under the picture.
