### ISSUE TITLE
INSTALL PFSENSE TO EL-20-3060-32G 

### ISSUE THREAD

**Issue by songhanpoo** [pfsense/docs#17]
Hi Team !

you can check my device link here : https://b2b.gigabyte.com/Embedded-Computing/EL-20-3060-32G-rev-10#ov

i have downloaded your source version 2.4.5 - 32 bit - usb memstick

i make install from usb boot - rufus 

when install i'm to be stuck " trying to mount root from ufs/dev/ufs/pfsense [ro]..."

i'm trying /sbin/init

pass step .

but i don't see my hdd into my device

can you help me ?

thanks for your reply.

**Comment by jim-p** [comment]
This is not a site for support. Please post to the forum at https://forum.netgate.com or to the pfSense subreddit at https://www.reddit.com/r/pfsense/
