### ISSUE TITLE
Internet Access Fails After install Softflow in PFsense 2.4.3-RELEASE-p1 (amd64) and previous version

### ISSUE THREAD

**Issue by hjc1175** [pfsense/docs#18]
Hello,

I Recently installed Softflowd 1.2.3 in Softflow in PFsense 2.4.3-RELEASE-p1 (amd64) and previous version, but internet connection failed, this is an known issue or made something wrong.

In Old version Softflowd working fine and Internet connection was monitoring well.

Please I really appreciate some info and guidence about this.

Thanks.

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
