### ISSUE TITLE
Unable to retrieve package information

### ISSUE THREAD

**Issue by bbusagroningen** [pfsense/docs#22]
I'm running nanoBSD 2.3.5 version of pfSense, and when I try to install any packages I get the following error message. 
![screen shot 2018-07-06 at 00 40 33](https://user-images.githubusercontent.com/21987084/42351461-59295f9e-80b5-11e8-860a-e638bc9e6ec2.jpg)

Any idea, how could I install any of the packages?

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
