### ISSUE TITLE
Child process pid=75019 terminated abnormally: Segmentation fault in pfsense unable to update

### ISSUE THREAD

**Issue by stevenrunghen** [pfsense/docs#29]
im getting Child process pid=75019 terminated abnormally: Segmentation fault
pf left a pkg-static.core on var/run , im unable to update pf nor removing or adding any package, nothing is working please help.

**Comment by stevenrunghen** [comment]
Netgate SG-4860 - Serial: 1138170327 - Netgate Device ID: 1f7687e47fcda83883a8
Welcome to pfSense 2.4.2-RELEASE-p1 (amd64)

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
