### ISSUE TITLE
2.3.5p2 and 2.4.3p1 release notes missing

### ISSUE THREAD

**Issue by mintsoft** [pfsense/docs#3]
Hello,

It appears that during the move the release notes for 2.3.5-RELEASE-p2 and 2.4.3-RELEASE-p1 have been
missed in the migration.

THey used to be here:
https://www.netgate.com/docs/pfsense/index.php/2.4.3-p1_New_Features_and_Changes
https://doc.pfsense.org/index.php/2.3.5-p2_New_Features_and_Changes

but those links just 404 and the release blog post still references the old URLS:
https://www.netgate.com/blog/pfsense-2-4-3-release-p1-and-2-3-5-release-p2-now-available.html

They're not in the list here:
https://www.netgate.com/docs/pfsense/releases/index.html

**Comment by jim-p** [comment]
We are aware, we're working on it.

**Comment by jdillard** [comment]
Thanks for bringing that to our attention!

I have fixed those two links and I am working on migrating the rest of the "new" content that didn't make it in the migration.

**Comment by mintsoft** [comment]
Awesome, thanks for the quick fix!
