### ISSUE TITLE
Provide Developper Style Rules for Javascript code

### ISSUE THREAD

**Issue by Augustin-FL** [pfsense/docs#30]
Hello,
There is currently no Developper Rules for JavaScript in [netgate readTheDocs](https://www.netgate.com/docs/pfsense/development/developer-style-guide.html)

Since big part of pfSense is a Web UI, javascript language is quite used in the project and coding guidelines would be welcome, especially given [the strong freedom](https://martin-thoma.com/javascript-wtf/) of this language....

More specifically : 
- Is the usage of ES6 (eg, using ```let```, ```const``` keyword, javascript classes, iterators, etc...)  recommended or is it a bad practice (since it break old browsers) ?
- Should we use jquery functions or native javascript as much as possible?
- Should we bother with outdated/unsupported browser compatiblity (eg, IE9 and below...) ?

**Comment by jdillard** [comment]
good point. To answer those for now:

1. No, we don't use a transpiler currently.
2. Vanilla is preferred for simple operations, but jQuery is available to fall back on.
3. We don't support outdated/unsupported browsers.

**Comment by jim-p** [comment]
I'll drop a couple notes on that page. I don't think we have any hard/specific rules though, what @jdillard said is a good start at least.
