### ISSUE TITLE
pfsense seems to use the same MAC for similar devices in the ARP table

### ISSUE THREAD

**Issue by Spire81** [pfsense/docs#32]
![image](https://user-images.githubusercontent.com/30710927/43019508-f17b66d6-8bf8-11e8-9a6b-bf988d1d965d.png)
How do I fix this as I'm using static IP's and having an issue this makes it near impossible to diagnose

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
