### ISSUE TITLE
Proposal: combine troubleshooting content

### ISSUE THREAD

**Issue by jdillard** [pfsense/docs#33]
Seems like it would be a good idea to consolidate the following:

- [ ] Move [Troubleshooting Squid Package Disk Usage](https://www.netgate.com/docs/pfsense/cache-proxy/troubleshooting-squid-package-disk-usage.html) to a section of  [Troubleshooting the Squid Package](https://www.netgate.com/docs/pfsense/cache-proxy/squid-troubleshooting.html)
- [ ] Move [Troubleshooting Captive Portal Issues with Apple iOS Clients](https://www.netgate.com/docs/pfsense/captiveportal/troubleshooting-captive-portal-issues-with-apple-ios-clients.html) to a section of [Troubleshooting Captive Portal](https://www.netgate.com/docs/pfsense/captiveportal/captive-portal-troubleshooting.html)

And set up a redirects. Thoughts?

**Comment by jim-p** [comment]
Looks like a good move to me. Those smaller articles are not really large enough to warrant their own pages now. I seem to recall they were much larger in the past but the info on those pages was rendered obsolete.

**Comment by jdillard** [comment]
I don't have all the plumbing setup just yet, but moving forward we can put redirects in [pfsense-wiki-redirects.conf](https://github.com/pfsense/docs/blob/master/pfsense-wiki-redirects.conf) and it will automatically update the redirects list.

We'll probably want to add "Creating redirects" to the docs somewhere...
