### ISSUE TITLE
Feedback on High Availability — Configuring High Availability

### ISSUE THREAD

**Issue by mariov652** [pfsense/docs#48]
**Page:** https://www.netgate.com/docs/pfsense/highavailability/configuring-high-availability.html

**Feedback:**

Hi,

Reading this page on CARP, the sentence below does not correspond to the diagram example and makes the explanation confusing:

" The IP address of the primary cluster node LAN is 192.168.1.2 and the IP address of the secondary node LAN is 192.168.1.3."

In my opinion, should read:

" The IP address of the primary cluster node LAN is 192.168.1.1 and the IP address of the secondary node LAN is 192.168.1.2. The CARP Virtual IP Address shared between nodes will be 192.168.1.3"

Rgds,

**Comment by jim-p** [comment]
That diagram is old and that whole section is likely to be removed in favor of https://www.netgate.com/docs/pfsense/book/highavailability/example-redundant-configuration.html
