### ISSUE TITLE
Feedback on Development — Reporting Issues with pfSense Software

### ISSUE THREAD

**Issue by snetgh** [pfsense/docs#49]
**Page:** https://www.netgate.com/docs/pfsense/development/bug-reporting.html

**Feedback:**
The problem is about the FreeRadius MAC Address authentication. The FreeRadius MAC Address quota is not working. I assigned 100MB and the user of that MAC address used more the the 100MB without him being disconnected from the system but with the pfsense 2.4.3 and the earlier ones works fine . So I think that one should be fix because we use it as WISP.
thanks

**Comment by snetgh** [comment]
The problem is about the FreeRadius MAC Address authentication. The FreeRadius MAC Address quota is not working. I assigned 100MB and the user of that MAC address used more the the 100MB without him being disconnected from the system but with the pfsense 2.4.3 and the earlier ones works fine . So I think that one should be fix because we use it as WISP.
thanks

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
