### ISSUE TITLE
Feedback on Development — Requesting New pfSense Features

### ISSUE THREAD

**Issue by NickRT91** [pfsense/docs#50]
**Page:** https://www.netgate.com/docs/pfsense/development/requesting-new-pfsense-features.html

**Feedback:**
It would be pretty awesome and very useful to be able to order VLAN's via 'drag and drop'. I imagine something like the ability order rules.

Nothing to do with altering weights or priorities just cosmetic... When a new VLAN is created it's added to the bottom. I think dragging them into order would be rather useful instead of them being 100, 200, 300, 190. Would be able to drag the '190' to position 2. 100, 190, 200, 300.

Thank's.

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion, or for feature requests. Read the linked document again.
