### ISSUE TITLE
Feedback on Cache / Proxy — Tuning the Squid Package

### ISSUE THREAD

**Issue by UnR34L** [pfsense/docs#52]
**Page:** https://www.netgate.com/docs/pfsense/cache-proxy/squid-package-tuning.html#caching-windows-updates

**Feedback:**

Having semi-colons breaks squid, taking the them away will make it work as expected.

**Comment by UnR34L** [comment]
Also, it doesn't look like '-1' is valid, I believe it should be 'none'

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9380
