### ISSUE TITLE
Feedback on Installing and Upgrading — Writing Disk Images

### ISSUE THREAD

**Issue by alfonx** [pfsense/docs#53]
**Page:** https://www.netgate.com/docs/pfsense/hardware/writing-disk-images.html

**Feedback:**

Just my 5¢ ... Linux/Unix install: Wouldnt it be more failsave, to run a "sync" after dd-ing the image to a USB-Stick? Otherwise I fear that not all data is properly written to the USB-stick...

**Comment by jim-p** [comment]
Since it uses `dd` that should not be a concern. If it was writing to a mounted filesystem, perhaps.

**Comment by alfonx** [comment]
> It may depend on the state of the drive when you started, and whether it contained a valid filesystem mounted by the OS.

Yes that probably is relevant..... In my case the stick had a FAT filesystem on it, and I did the dd-cleanup
>sudo dd if=/dev/zero of=/dev/sdz bs=1M count=1
directly before I did the dd-copy...
