### ISSUE TITLE
Feedback on User Management — Configuring User Authentication Servers

### ISSUE THREAD

**Issue by lshantz** [pfsense/docs#55]
**Page:** https://www.netgate.com/docs/pfsense/usermanager/user-authentication-servers.html

**Feedback:**

"RADIUS NAS IP Attribute"

Please consider adding more detail on this new feature. It isn't clear on which interface should be selected. You choices are WAN (with pretermined IP address) or LAN. In my case there is also a pfb interface, but that is obviously not the correct one.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9372
