### ISSUE TITLE
Feedback on User Management — Testing the FreeRADIUS Package

### ISSUE THREAD

**Issue by nshantz** [pfsense/docs#56]
**Page:** https://www.netgate.com/docs/pfsense/usermanager/testing-freeradius.html

**Feedback:**

In the radius text... you show how to test from the shell. There is a very simple way to test using the gui. GO to Diagnostics/Authentication. Change authentication server to freeradius, then enter your name and you can even use your pin+google authentication code. If you have it set up correctly it will give you succeeded.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9371
