### ISSUE TITLE
Mac Computer Names

### ISSUE THREAD

**Issue by hessercan** [pfsense/docs#57]
![screen shot 2018-10-18 at 10 47 19 pm](https://user-images.githubusercontent.com/24305438/47195006-c6f60f80-d327-11e8-99ea-e8abd302b5a3.png)
So I've had this issue where my Mac thinks that there is another computer on the network with it's name and in turn added a (2) to the name. But as I looked around the network, my Apple TV was all the way up to a (10). So there is a loop somewhere causing this to happen. I have had to disable this plugin completely just to get it to stop. Any help would be amazing!

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).

**Comment by hessercan** [comment]
I thought this was a thread was for issues... is this not an issue? Or am I missing something obvious.

**Comment by jim-p** [comment]
This issue tracker is for problems with or enhancements to the online documentation only (it's under "docs").

See https://www.netgate.com/docs/pfsense/development/bug-reporting.html

**Comment by hessercan** [comment]
ah, I see that now. My bad.
