### ISSUE TITLE
Feedback on Installing and Upgrading — Installing pfSense Over an Existing FreeBSD Installation

### ISSUE THREAD

**Issue by lshantz** [pfsense/docs#58]
**Page:** https://www.netgate.com/docs/pfsense/install/installing-pfsense-over-an-existing-freebsd-installation.html

**Feedback:**
Installing pfSense Over an Existing FreeBSD Installation

No. pfSense is a customized v

Seriously!?!? This makes no sense. I'm looking for the keystrokes to start the install process. The answer no to the header makes no sense. This needs revising.

**Comment by jim-p** [comment]
It is correct. You cannot install pfSense on top of an existing FreeBSD installation.

You need to boot the pfSense install media and it will automatically launch the installer. This process will overwrite any existing operating system on the target disk,
