### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by jdillard** [pfsense/docs#6]
Some of the icons still need to be updated to use the font-awesome icons, you can see some here: https://www.netgate.com/docs/pfsense/config/shortcut-bar.html

They are referenced here: https://github.com/pfsense/docs/blob/master/source/substitutions.rsti

And stored here: https://github.com/pfsense/docs/tree/master/source/_static/icons

**Comment by jim-p** [comment]
I added substitutions for all of the new fa- icons and separated out the old icons in 6cce6ab99169816b5d08b2d6b12e0c4a48c393a2

**Comment by jim-p** [comment]
I got through most of these, only a handful more to clean up and I'll do those tomorrow.
