### ISSUE TITLE
Feedback on Packages — Stunnel package

### ISSUE THREAD

**Issue by alteredstate82** [pfsense/docs#64]
**Page:** https://www.netgate.com/docs/pfsense/packages/stunnel-package.html

**Feedback:** Using the STunnel 5.37_1 package in pfSense 2.4.4 I have an issue where STunnel is not separating the: "-----END PRIVATE KEY-----" and "-----BEGIN CERTIFICATE-----".  I believe this is only happening when I use an imported certificate using: `"System --> Cert. Manager --> Certificates --> +Add/Sign --> Method --> Import an existing Certificate"`.  Looking at that certificate's PEM file:

`cat /usr/local/etc/stunnel/'mycertfile'.pem`
 
I see this:
```
....Xhnsugqd
-----END PRIVATE KEY----------BEGIN CERTIFICATE-----
MIIGaTCCB....
```
After I change it to this:
```
....Xhnsugqd
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MIIGaTCCB....
```
then STunnel will start.  The problem is that after a pfSense reboot or reload the PEM file reverts back.  There is also an issue where: `/var/tmp/stunnel/` will disappear after a pfSense reboot and then must be re-created before STunnel will start.  Other than that, STunnel works great!  Would you be able to correct these issues?

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).

See [Reporting Issues with pfSense Software](https://www.netgate.com/docs/pfsense/development/bug-reporting.html) for more information.

**Comment by alteredstate82** [comment]
![image](https://user-images.githubusercontent.com/1347203/48433262-b2e5d800-e744-11e8-98f7-751574afd8ac.png)

That was pulled from the [pfSense STunnel package](https://www.netgate.com/docs/pfsense/packages/stunnel-package.html) page.  Yes, there appears to be definitely something wrong with the STunnel package as it's making changes to the PEM file that are incorrect.  The problem has already been solved by me...now I'm asking that it be corrected in the package.

**Comment by jim-p** [comment]
The text in the image doesn't disagree with what I said.

If there is something wrong or missing in the text of the documentation, you can report it here. But as the first sentence says, for assistance with solving problems, use the forum. This is a problem/bug/whatever, _not_ a documentation issue. This issue tracker is _only_ for documentation, not software.

**Comment by alteredstate82** [comment]
I do apologize!  I was under the assumption it was for the package itself.
