### ISSUE TITLE
Feedback on Development — Requesting New pfSense Features

### ISSUE THREAD

**Issue by warhansen** [pfsense/docs#65]
**Page:** https://www.netgate.com/docs/pfsense/development/requesting-new-pfsense-features.html

**Feedback:**

Hi, I would like to request a full feature, or at the very least a plugin, to setup equal bandwidth sharing. I have researched quite a bit and it seems none the options work very well. It is also something many people are asking for. Can you add an option or a tick box under networking where one can just select "Equal Internet Bandwidth Sharing" and it then does all the configuration to divide internet bandwidth by each IP requesting internet traffic. If an IP has no internet traffic, the rest of the IP's on the network share the bandwidth. In other words if 5 IP's are downloading a large file, the bandwidth must be shared by all 5 equally. If one is not download the internet bandwidth must be shared by 4 and so on. If there is only 1 IP requesting internet traffic it gets 100% of the bandwidth until another IP starts a internet traffic request.

Thank you.

Warren

**Comment by jim-p** [comment]
This site is not for feature requests, support, or diagnostic discussion.

Please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/) to discuss the new feature as there may already be a request for it.

Read the content of [Requesting New pfSense Features](https://www.netgate.com/docs/pfsense/development/requesting-new-pfsense-features.html) for more information.
