### ISSUE TITLE
Feedback on Packages — Configuring the Snort Package

### ISSUE THREAD

**Issue by lshantz** [pfsense/docs#66]
**Page:** https://www.netgate.com/docs/pfsense/ids-ips/setup-snort-package.html

**Feedback:**

There really needs to be a "Snort" forum to talk about problems. Currently it is NOT listed. Pfblocker is, but not Snort.

**Comment by jim-p** [comment]
https://forum.netgate.com/category/53/ids-ips

**Comment by lshantz** [comment]
Oh that is sooo helpful! It is BROKE. But no worries don't fix it. I expected that

    On Monday, November 19, 2018, 12:46:20 PM MST, Jim P <notifications@github.com> wrote:  
 
 
https://forum.netgate.com/category/53/ids-ips

**Comment by jim-p** [comment]
This site is for problems with the documentation, not feature requests or forum issues. The link I provided is for the IDS/IPS area of the Netgate forum, which is specifically for Snort and Suricata, and it works fine. If you have a problem reaching it, try contacting the support team at https://go.netgate.com/
