### ISSUE TITLE
Feedback on Services — DNS — Configuring the DNS Resolver

### ISSUE THREAD

**Issue by javier-cr** [pfsense/docs#67]
**Page:** https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html

**Feedback:** Add sections describing behavior of the two SSL/TLS service options present on this docs page.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9373
