### ISSUE TITLE
Feedback on Virtualization — Virtualizing pfSense with Hyper-V

### ISSUE THREAD

**Issue by ghost** [pfsense/docs#70]
**Page:** https://www.netgate.com/docs/pfsense/virtualization/virtualizing-pfsense-with-hyper-v.html

**Feedback:**

The Hyper-V tutorial doesn't make a lot of sense. I know there is a generic disclaimer about not looking to hard at it, however the first two steps will probably cause more confusion then less.

Currently it asks you to create an internal network in step one, then immediately change it to a private network in step two. A vswitch cannot be internal and private at the same time, so it might as well just say to create a private interface in step 1, and remove step 2 completely.

Secondly, a private interface isn't a good idea here because it only works on the VM in question. Internal will only work with the other VMs running in Hyper-V. Why not just use external w/ a dedicated NIC as this is what is needed for most if not all real world setups?

Also if you do not turn off the Backup (VSS) integration service for the pfSense VM, it will cause an error when you reboot the host, which causes a hard reset of the pfSense VM instead of a graceful shutdown, which could corrupt data on disk.

pfSense also now works with a Hyper-V Gen2 VM with a little tweaking, so maybe that should be included? Not necessary but still something to consider.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9374
