### ISSUE TITLE
Feedback on VPN — OpenVPN — Troubleshooting OpenVPN Internal Routing (iroute)

### ISSUE THREAD

**Issue by dharmatma** [pfsense/docs#71]
**Page:** https://www.netgate.com/docs/pfsense/vpn/openvpn/troubleshooting-openvpn-internal-routing-iroute.html

**Feedback:**

> For each network that needs an iroute statement, the server definition must also have the same network(s) listed as IPv4/IPv6 Remote Networks or as route statements in the advanced options box.

In the server section there is no " IPv4/IPv6 Remote Networks" field. 
Version: 2.4.4-RELEASE-p1

**Comment by jim-p** [comment]
Then you do not have the VPN in the mode stated on the page. That box appears for Peer to Peer SSL/TLS mode only. iroutes do not typically make sense for Remote Access style VPNs.

If you need more clarification/assistance, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).
