### ISSUE TITLE
Feedback on ACME - no info on how to use cron 

### ISSUE THREAD

**Issue by yuriw** [pfsense/docs#72]
The docs state `The ACME package automates this renewal by using a cron job to check once per day to see if a certificate needs to be renewed.` 
(see https://www.netgate.com/docs/pfsense/certificates/acme-package.html#acme-package), 
however there is no explanation where and how to do this.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9375
