### ISSUE TITLE
Feedback on System Monitoring — Filter Log Format for pfSense 2.2

### ISSUE THREAD

**Issue by bbrendon** [pfsense/docs#73]
**Page:** https://www.netgate.com/docs/pfsense/monitoring/filter-log-format-for-pfsense-2-2.html

**Feedback:**

This is incorrect...
`<action> ::= "pass" | "block" -- Action taken that resulted in the log entry`

Action can also have the value of `unkn(%u)`

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9376
