### ISSUE TITLE
log file format : missing igmp.  <protocol-specific-data> ::= <tcp-data> | <udp-data> | <icmp-data> | <carp-data>

### ISSUE THREAD

**Issue by bbrendon** [pfsense/docs#74]
**Page:** https://www.netgate.com/docs/pfsense/monitoring/filter-log-format-for-pfsense-2-2.html

**Feedback:**
`<protocol-specific-data> ::= <tcp-data> | <udp-data> | <icmp-data> | <carp-data>`

The above is missing igmp-data

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9377
