### ISSUE TITLE
unbound documentation suggests using unbound-control but it's not enabled by default

### ISSUE THREAD

**Issue by jawz101** [pfsense/docs#8]
https://www.netgate.com/docs/pfsense/dns/unbound-dns-resolver.html#additional-notes

when I issue unbound-control commands in terminal I get

ex: I was trying to use `unbound-control dump_cache`

> unbound-control[51556:0] warning: control-enable is 'no' in the config file.

I'm guessing you need to enable it by putting `control-enable: "yes"` under
    Services / DNS Resolver / General Settings /  Custom options ?

Either way, it would be nice to have some sort of note to say how to get it to work

**Comment by jim-p** [comment]
Read the note at the bottom of that page. You must pass `-c /var/unbound/unbound.conf` to unbound-control to get it to work.

**Comment by jawz101** [comment]
> To determine the name servers that will be queried to lookup a zone:
>     unbound-control lookup “name”
> Note: unbound in pfsense does not use the default conf file location, so will need tell it where it is.
>     unbound-control -c /var/unbound/unbound.conf command


That doesn't read like it necessarily explains why the unbound-control command doesn't work.
Perhaps

> Note: Issue the unbound-control command with the following option as the unbound.conf file in pfsense is not in the default conf file location.
