### ISSUE TITLE
Feedback on Certificate Management — ACME package — Wildcard Certificates

### ISSUE THREAD

**Issue by Prowler2** [pfsense/docs#83]
**Page:** https://www.netgate.com/docs/pfsense/certificates/acme-wildcard.html

**Feedback:**
The instructions say to add both the domain and the wildcard version of the same domain in the SAN list. This results in an error stating that you can only put the wildcard domain or the domain (not both)

**Comment by jim-p** [comment]
I can't reproduce this here. I have a couple test wildcard certs and they both have, for example `foo.example.com` and `*.foo.example.com` as separate entries in the **Domain SAN List** and they work.

Please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/) to discuss your issue in more detail.
