### ISSUE TITLE
Feedback on Virtualization — Virtualizing pfSense with Proxmox

### ISSUE THREAD

**Issue by marijnv2000** [pfsense/docs#84]
**Page:** https://www.netgate.com/docs/pfsense/virtualization/virtualizing-pfsense-with-proxmox.html

**Feedback:**
In the end of the guide, it states that you should check the "Disable hardware checksum offload" box. I had not done this yet, as I thought it would just solve a sluggish web-interface (as stated) which I wasn't experiencing. When my DNS didn't work on any Proxmox guests, I asked around and someone told me that I had to check that box, as "pretty much routing anything other than icmp will fail, you'll get massive packet loss". It might be helpful to include that in the guide, so other people like me won't skip the final step thinking they don't need it. The reason I'm not filing a pull request is because I don't know enough about this, and I don't want to provide wrong information.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9378
