### ISSUE TITLE
Feedback on Interfaces — Using a Large Number of Interfaces

### ISSUE THREAD

**Issue by jdekker-netgate** [pfsense/docs#85]
**Page:** https://docs.netgate.com/pfsense/en/latest/interfaces/using-a-large-number-of-interfaces.html

**Feedback:** 

> Using a Large Number of Interfaces

>**There is no limit we are aware of.** There are multiple installations with more than 50 interfaces (VLANs). If there are many interface tabs, a drop-down list is presented. There may be some quirks in the GUI with certain themes, and some areas may take longer to display and process, but it does function. We have received reports of systems with thousands of interfaces that are still usable.

We have seen multiple support tickets about issues stemming from users with hundreds of VLAN interfaces assigned (INC-20454 probably being the most recent). Issues really seem to begin as the number of interfaces approaches 200. It seems like 128 interfaces would be a good limit to suggest, to prevent any performance related issues.

**Comment by jdillard** [comment]
In order to consolidate where pfSense issues are tracked, we are moving the Github issues to Redmine. This issue is now being tracked at https://redmine.pfsense.org/issues/9379
