### ISSUE TITLE
Feedback on Certificate Management — ACME package

### ISSUE THREAD

**Issue by ComMoMike** [pfsense/docs#87]
**Page:** https://www.netgate.com/docs/pfsense/certificates/acme-package.html

**Feedback:**
Hi,
first of, thanks for the nice plugin. I ran into an error: I issued a certificate for my virtual firewall hosted by an internet provider, pfSense 2.4.4, ACME package 0.5.4, no other packages installed. Everything went well but the certificate isn´t accepted as secure by any (Mac-)browser I´ve tested. They all complain that it is validated by "Fake LE Intermediate X1". After a quick internet search I´ve learned that this is because the plugin uses the staging server instead of the production server. You can find the discussion here:
<https://community.letsencrypt.org/t/cn-fake-le-intermediate-x1/13437>
It would be nice if you could fix this.

Best regards,

Mike Bobkiewicz

**Comment by jim-p** [comment]
This site is not for support or diagnostic discussion.

For assistance in solving problems, please post on the [Netgate Forum](https://forum.netgate.com) or the [pfSense Subreddit](https://www.reddit.com/r/pfSense/).

See [Reporting Issues with pfSense Software](https://www.netgate.com/docs/pfsense/development/bug-reporting.html) for more information.
